Fix non-constant initializer to static variable
The alignof macro used in type_alignof is not actually a constant
expression (legally, the use of an address of a runtime variable like
cC/cs/ci/etc. makes it a non-constant expression), so this fails to
compile under compilers which do not implement an extension to
consider its invocations here as constant expressions:

type.c: In function 'type_alignof':
type.c:468:27: error: initializer element is not constant
  468 | #define alignof(field,st) ((size_t) ((char*) &st.field - (char*) &st))
      |                           ^
type.c:486:40: note: in expansion of macro 'alignof'
  486 |         static size_t char_alignment = alignof(C, cC);
      |                                        ^~~~~~~

This commit fixes this by simply making the [type]_alignment variables
into non-static variables, which removes the requirement for a
constant expression and works perfectly fine here (the presence of
`static` here beforehand doesn't seem to have been particularly
useful, as the variable is not modified further at any point ¯\_(ツ)_/¯)